---
- name: "Create certs folder"
  file:
    path: "{{ certs_path }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0750

- name: "Copy ca.crt from /tmp to {{ ca_path }}"
  copy:
    remote_src: true
    src: "/tmp/ca/ca.crt"
    dest: "{{ ca_path }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
  notify: restart_elasticsearch