---
- set_fact:
    cert_name: "{{ cert_name }}-{{ ansible_host }}"

- name: "Generating certificate for"
  debug:
    msg: "{{ cert_dns }} ({{ cert_ip }}): {{ cert_name }}"

- name: "Check if certificate already exists in /tmp"
  stat:
    path: "/tmp/{{ cert_name }}.zip"
  register: result
  changed_when: no
  delegate_to: es01

- name: Generate certificate
  shell: "{{ share_path }}/bin/elasticsearch-certutil cert --pem --ca-cert {{ ca_cert_path }} --ca-key {{ ca_key_path }} \
      --ca-pass {{ elastic_stack.ca_pass }} --dns localhost,{{ cert_dns }} --ip 127.0.0.1,{{ cert_ip }} --name {{ cert_name }} --out /tmp/{{ cert_name }}.zip --silent"
  when: result is not undefined and result.stat.exists == false
  delegate_to: es01

- name: Copy certificate to controller
  fetch: 
    src: "/tmp/{{ cert_name }}.zip"
    dest: "/tmp/"
    flat: true
  delegate_to: es01