---
- set_fact:
    cert_ip: "{{ hostvars[ansible_host]['ansible_default_ipv4']['address'] }}"
    cert_dns: "{{ ansible_host }}"
    cert_name: "{{ elastic_stack.cert_name }}"
    cert_name_host: "{{ elastic_stack.cert_name }}-{{ ansible_host }}"

- name: "Generating certificate for"
  debug:
    msg: "{{ cert_dns }} ({{ cert_ip }}): {{ cert_name_host }}"
  delegate_to: es01

- name: "Check if certificate already exists in /tmp on es01"
  stat:
    path: "/tmp/{{ cert_name_host }}.zip"
  register: result
  changed_when: no
  delegate_to: es01

- name: Generate certificate on es01
  shell: "{{ share_path }}/bin/elasticsearch-certutil cert --pem --ca-cert {{ ca_cert_path }} --ca-key {{ ca_key_path }} \
      --ca-pass {{ elastic_stack.ca_pass }} --dns localhost,{{ cert_dns }} --ip 127.0.0.1,{{ cert_ip }} --name {{ cert_name_host }} --out /tmp/{{ cert_name_host }}.zip --silent"
  when: result is not undefined and result.stat.exists == false
  delegate_to: es01

- name: Copy certificate to controller
  fetch: 
    src: "/tmp/{{ cert_name_host }}.zip"
    dest: "/tmp/"
    flat: true
  delegate_to: es01