---
- name: "Check if /tmp/{{ elastic_stack.ca_name }}.zip already exists"
  stat:
    path: "/tmp/{{ elastic_stack.ca_name }}.zip"
  register: result

- name: "Generate CA {{ elastic_stack.ca_name }}"
  shell: "{{ share_path }}/bin/elasticsearch-certutil ca --pem --out /tmp/{{ elastic_stack.ca_name }}.zip --pass {{ elastic_stack.ca_pass }} --silent"
  when: result is not undefined and result.stat.exists == false

- name: Copy CA to controller
  fetch: 
    src: "/tmp/{{ elastic_stack.ca_name }}.zip"
    dest: /tmp/
    flat: true