---
- name: "Reset elastic password"
  shell: "{{ share_path }}/bin/elasticsearch-reset-password -u elastic --batch --force --silent"
  register: result

- name: Generated password
  debug:
    var: result.stdout

- name: Set elastic new password
  vars:
    generated_password: "{{ result.stdout }}"
    password: "{{ account_password.elastic }}"
  uri:
    url: https://localhost:9200/_security/user/_password
    method: PUT
    url_username: elastic
    url_password: "{{ generated_password }}"
    validate_certs: false
    body_format: json
    body: "{{ lookup('template','password.json.j2') }}"
    headers:
      Content-Type: "application/json"