---
- name: "Set {{ username }} password"
  uri:
    url: "https://localhost:9200/_security/user/{{ username }}/_password"
    method: PUT
    url_username: elastic
    url_password: "{{ account_password.elastic }}"
    validate_certs: false
    body_format: json
    body: "{{ lookup('template','password.json.j2') }}"
    headers:
      Content-Type: "application/json"