---
vm: 
  max_map_count: 262144
  swappiness: 1

pam_limits:
  nofile: 65535
  nproc: 4096
  memlock: unlimited

etc_path: /etc/elasticsearch
share_path: /usr/share/elasticsearch
service_path: /etc/systemd/system/elasticsearch.service.d

certs_path: "{{ etc_path }}/certs"
transport_cert: "elastic-cert"
http_cert: "elastic-cert"

ca_cert_path: "{{ certs_path }}/{{ elastic_stack.ca_name }}.crt"
ca_key_path: "{{ certs_path }}/{{ elastic_stack.ca_name }}.key"

owner: root
group: elasticsearch