---
- name: Collect facts for tags needing them (gathering facts is not done when using tags)
  hosts: all
  tags: [cfg, certs] 
  tasks:
    - setup:
        gather_timeout: 10 

- name: "Prepare hosts"
  hosts: all,!hypervisor
  become: true
  tags: [os]
  roles:    
    - { role: tooling/repository, mode: "remove-elastic_{{ ansible_os_family}}" }
    - { role: tooling/os, mode: "full-upgrade_{{ ansible_os_family}}" }

- name: "Deploy elasticsearch nodes"
  hosts: elasticsearch
  become: true
  tags: [es]
  roles:
    - { role: elasticsearch, mode: apply-prerequisites }
    - { role: tooling/repository, mode: "add-elastic_{{ ansible_os_family }}" }
    - { role: tooling/service, mode: install, service_name: elasticsearch, service_version: "{{ elastic_stack.version }}" }
    - { role: elasticsearch, mode: service-override }
    - { role: tooling/repository, mode: "remove-elastic_{{ ansible_os_family }}" }
    - { role: elasticsearch, mode: set-configuration, tags: cfg }
    - { role: elasticsearch, mode: generate-ca, when: "ansible_host in groups['elasticsearch'][0]", tags: certs }
    - { role: tooling/certificate, mode: extract-ca, tags: certs }
    - { role: elasticsearch, mode: deploy-ca, tags: certs }
    - { role: elasticsearch, mode: clean-auto-generated-certs, tags: certs }
    - { role: elasticsearch, mode: generate-certs, tags: certs }
    - { role: tooling/service, mode: start, service_name: elasticsearch }
    - { role: elasticsearch, mode: wait-for-start }

# - name: "Install CA on Hypervisor"
#   hosts: hypervisor
#   become: true
#   tags: [ca]
#   roles:
#     - { role: tooling/certificate, mode: install-ca, tags: certs }

- name: "Configure passwords"
  hosts: elasticsearch[0]
  become: true
  tags: [pwd]
  roles:
    - { role: elasticsearch, mode: reset-elastic-password, tags: es }
    - { role: elasticsearch, mode: set-password, username: "kibana_system", password: "{{ account_password.kibana_system }}", tags: kbn }
    - { role: elasticsearch, mode: set-password, username: "remote_monitoring_user", password: "{{ account_password.remote_monitoring_user }}", tags: mon }

- name: "Deploy kibana"
  hosts: kibana
  become: true
  tags: [kbn]
  roles:
    - { role: tooling/repository, mode: "add-elastic_{{ ansible_os_family }}" }
    - { role: tooling/service, mode: install, service_name: kibana, service_version: "{{ elastic_stack.version }}" }
    - { role: tooling/repository, mode: "remove-elastic_{{ ansible_os_family }}" }
    - { role: kibana, mode: set-configuration, tags: cfg }
    - { role: tooling/certificate, mode: extract-ca, tags: certs }
    - { role: kibana, mode: deploy-ca, tags: certs }
    - { role: tooling/service, mode: start, service_name: kibana }
    - { role: kibana, mode: wait-for-start }

- name: "Deploy monitoring"
  hosts: all,!hypervisor
  become: true
  tags: [mon]
  roles:    
    - { role: tooling/repository, mode: "add-elastic_{{ ansible_os_family }}" }
    - { role: tooling/service, mode: install, service_name: filebeat, service_version: "{{ elastic_stack.version }}" }
    - { role: tooling/service, mode: install, service_name: metricbeat, service_version: "{{ elastic_stack.version }}" }
    - { role: tooling/repository, mode: "remove-elastic_{{ ansible_os_family }}" }
    - { role: monitoring/filebeat, mode: set-configuration, tags: cfg }
    - { role: monitoring/metricbeat, mode: set-configuration, tags: cfg }
    - { role: tooling/certificate, mode: extract-ca, tags: certs }
    - { role: monitoring/filebeat, mode: deploy-ca, tags: certs }
    - { role: monitoring/metricbeat, mode: deploy-ca, tags: certs }
    - { role: tooling/service, mode: start, service_name: filebeat }
    - { role: tooling/service, mode: start, service_name: metricbeat }