---
base_image_variant: ubuntu22.04
base_image_name: noble-server-cloudimg-amd64.img
base_image_url: https://cloud-images.ubuntu.com/noble/current/{{ base_image_name }}
base_image_sha: aa3c3b879cce2a9a5c0b915fc928d981f4044603d4ae51cb36c9067985119ba3

libvirt_images_dir: "/var/lib/libvirt/images"
libvirt_vms_dir: "/var/lib/libvirt/vms"

ssh_key_file: ~/.ssh/id_rsa
ssh_key_passphrase: ""