- name: "Ensure VMs are started"
  virt:
    name: "{{ current_vm_name }}"
    state: running
  with_items: "{{ hostvars }}"
  loop_control:
    loop_var: current_vm_name
    label: "{{ current_vm_name }}"
  when: current_vm_name != "localhost"
  register: result
  until: "result is success"
  retries: 15
  delay: 2

- name: Pause to wait for VM to start
  pause:
    seconds: 30
  when: result.changed == true