---
- name: "Create certs folder"
  file:
    path: "{{ certs_path }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0750

- name: "Copy certificate crt and key from /tmp on controller to {{ certs_path }}"
  copy:
    src: "/tmp/{{ cert_name }}/{{ cert_name }}/"
    dest: "{{ certs_path }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
  notify: restart_fleet_server