---

- name: "Enroll elastic agent"
  debug:
    msg: "elastic-agent enroll -f --url=https://fs01:8220 --fleet-server-es=https://es01:9200 --fleet-server-policy=fleet_server_policy --fleet-server-host=0.0.0.0 --fleet-server-port=8220 --fleet-server-service-token={{ service_token }} --fleet-server-es-ca={{ ca_cert_path }} --certificate-authorities={{ ca_cert_path }} --fleet-server-cert={{ certs_path }}/{{ cert_name }}-{{ ansible_host }}.crt --fleet-server-cert-key={{ certs_path }}/{{ cert_name }}-{{ ansible_host }}.key"

- name: "Enroll elastic agent"
  shell: "elastic-agent enroll -f --url=https://fs01:8220 --fleet-server-es=https://es01:9200 --fleet-server-policy=fleet_server_policy --fleet-server-host=0.0.0.0 --fleet-server-port=8220 --fleet-server-service-token={{ service_token }} --fleet-server-es-ca={{ ca_cert_path }} --certificate-authorities={{ ca_cert_path }} --fleet-server-cert={{ certs_path }}/{{ cert_name }}-{{ ansible_host }}.crt --fleet-server-cert-key={{ certs_path }}/{{ cert_name }}-{{ ansible_host }}.key"
  register: result

- name: Enrollment result
  debug:
    var: result.stdout