---
etc_path: /etc/elastic-agent
share_path: /usr/share/elastic-agent

certs_path: "{{ etc_path }}/certs"

ca_cert_path: "{{ certs_path }}/{{ elastic_stack.ca_name }}.crt"

cert_path: "{{ certs_path }}/{{ elastic_stack.cert_name }}.crt"
key_path: "{{ certs_path }}/{{ elastic_stack.cert_name }}.key"

owner: root
group: root