---
kvm:
  users: [ingrid]

vms:
  root_pass: root
  default_user: ubuntu
  default_pass: ubuntu
  network_name: default
  domain_name: domain.local
  elasticsearch:
    - name: hot
      disk: 20G
      mem: 4096
      cpu: 2
    - name: warm
      disk: 30G
      mem: 4096
      cpu: 2
  other:
    - name: kibana
      disk: 10G
      mem: 1024
      cpu: 1
    - name: fleet-server
      disk: 10G
      mem: 512
      cpu: 1
    # - name: apm-server
    #   disk: 10G
    #   mem: 512
    #   cpu: 1
    # - name: logstash
    #   disk: 10G
    #   mem: 1024
    #   cpu: 1
    # - name: search
    #   disk: 10G
    #   mem: 1024
    #   cpu: 1